config/routes.rb
Rails.application.routes.draw do
  get 'add_to_cart' => 'cart#add_to_cart'
  get 'view_order' => 'cart#view_order'
  get 'checkout' => 'cart#checkout'
  resources :orders
  resources :line_items
  devise_for :users
  root 'storefront#all_items'
  get 'categorical' => 'storefront#items_by_category'
  get 'branding' => 'storefront#items_by_brand'
  post 'order_complete' => 'cart#order_complete'
  resources :categories
  resources :products

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ritazone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <%= link_to "Ritazone", root_path, class: "navbar-brand" %>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-left">
          <li><%= link_to "All Items", root_path %></li>
          <li><%= link_to "Items by Category", categorical_path %></li>
          <li><%= link_to "Items by Brand", branding_path %></li>
          <!-- By Category -->
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Find by Category <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <% @categories.all.each do |cat| %>
                <li><%= link_to cat.name, categorical_path(cat_id: cat.id) %></li>
              <% end %>
            

            <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Categories <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <% @categories.each do |cat| %>
            <li><%= link_to cat.name, categories_path(cat_id: cat.id) %></li>
            <% end %>
            </ul>
          </li>
          <!-- By Brand -->
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Find by Brand <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="/">All</a></li>
            </ul>
          </li>        
          
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          <% else %>
           <li><%= link_to "Sign In",  new_user_session_path %></li>
            <li><%= link_to "Sign Up",  new_user_registration_path %></li>
          <li><%= link_to "Forgot Password",  new_user_password_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

<div class="container">
<%= yield %>
</div>

</body>
</html>